apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-deploy
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-deploy-run-
      spec:
        pipelineRef:
          name: build-deploy
        params:
          - name: revision
            value: $(params.gitrevision)
          - name: repo-url
            value: $(params.gitrepositoryurl)
