---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    metadata:
      name: hello-v1
    spec:
      containers:
        - env:
            - name: TARGET
              value: World from v1
          image: gcr.io/knative-samples/helloworld-go
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    metadata:
      name: hello-v2
    spec:
      containers:
        - env:
            - name: TARGET
              value: Knative from v2
          image: gcr.io/knative-samples/helloworld-go
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    metadata:
      name: hello-v3
    spec:
      containers:
        - env:
            - name: TARGET
              value: OSS NA 2020 from v3
          image: gcr.io/knative-samples/helloworld-go
  traffic:
    - latestRevision: false
      percent: 0
      revisionName: hello-v1
      tag: v1
    - latestRevision: false
      percent: 0
      revisionName: hello-v2
      tag: v2
    - latestRevision: true
      percent: 100
      tag: v3
